### PR TITLE
Major refactoring

### PR DESCRIPTION
**Pull request by flleeppyy**
Not yet ready for merging, but ready for review.

My motto for this commit? "Presentation Matters"

I made this PR since I saw a lot of disorganization, and stuff was kind of all over the place.

This PR has major changes, and changes the whole structure of the project.
- Added issue templates from @sysdotini's Hibiki repo (https://github.com/sysdotini/hibiki) Slightly modified
- Installed prettier and eslint, use `npm run lint`
- Heavily improved the readme.
- Fixed some grammar in the extensions.
- - We should consider making the extension one folder, and have it build for firefox and chrome, just so we don't have duplicate code.
- purpleFlowString has been changed to PurpleServiceWorker, as that is what it seems to be, and moved to its own monorepo
- - It can be built with `npm run worker:build`. It will output to `chrome/` and `purpleServiceWorker/dist/`
- - `npm run worker:build:nocopy` will not copy to `chrome/`
- Web server has been changed into a monorepo, and changed to Typescript.
- - To run in development, run `npm run server:dev`, to build and run for production, run `npm run server:build` then `npm run server:start`
- - Added `fetchClientId` which downloads a Twitch file and grabs the clientId, incase its ever changed.
- - Added pino logger. (Need to remove express integration so it doesn't spam the console)
- - node-fetch/cross-fetch doesn't support "agent" anymore, there will have to be some changes in that area.
- - Removed SSL code - Use Nginx/Caddy with reverse_proxy instead.
- - Added `helmet` and `cors` with `*` options (This removes the unnecessary `setHeader`, `removeHeader`, etc. code)
- - Added a rate limit, will probably remove it because I realized after testing that the web server *IS* the proxy
- - Removed requests that specified the content return type, as its interpreted and set by express automatically.
- - `GET`ing the root page will now return some basic information about the web server.
- - Added dotenv and a `.env.example` file, copy/paste it and rename it to .env and change it.

To-do: 
- [x] Add CONTRIBUTING.md
- [x] Move development instructions from readme to CONTRIBUTING.md
- [x] Remove logging from debugging in the server
- [x] Remove ratelimit
- [x] Add lint-staged
- [x] Update .gitignore

### CODE REVIEW

**Comment by flleeppyy** [comment]
I'd like to apologize for dropping in with this PR so suddenly, especially such a massive one. 

This is an awesome project, and I saw an opportunity to improve it. I hope you're okay with these changes, which overall make the code cleaner, more presentable and easier to work with from a developer standpoint. 

At some point, I'd like to make a PR that merges the chrome and firefox extensions into one, with build scripts for the seperate browsers.

**Comment by arthurbolsoni** [comment]
You don't know how much I'm happy for your collaboration, I'll find a little time in my day to study the changes as soon as possible :)

**Comment by flleeppyy** [comment]
Sounds good! Oh, if you'd like me to work on tests, and possibly re-implementing the proxy in the web server, please do let me know!

**Comment by flleeppyy** [comment]
Could you do me a favor and tell me what your npm and node version is?
`npm --version`
`node --version`

**Comment by arthurbolsoni** [comment]
NODEJS : v14.17.6
NPM: 6.14.15

**Comment by flleeppyy** [comment]
Oh dear...
Could you please update your npm version?
`sudo npm i -g npm@latest` or just `npm i -g npm@latest` if you're on windows

**Comment by arthurbolsoni** [comment]
done!
NPM: 8.3.2

**Pull request merged**
